// tests/attestation/roundtrip.test.ts — T5 ROUND-TRIP ACCEPTANCE, the money gate
// (spec specs/2026-07-19-gateway-attestation-evidence-design.md §5-1/§5-6, plan T5).
//
// The whole point of the attestation-evidence arc is that a REAL gateway's
// persisted evidence survives the REAL verifier — not that sov's tests agree
// with sov. So this suite:
//
//   1. boots the gateway harness with a REAL decorum pack + attestation
//      {enabled, io} (scripts/attestation-roundtrip.ts — the same wiring
//      `sov gateway` performs at boot), drives the six governed turn shapes
//      (clean pass / redact-replace / output block / regenerate / pregate-deny
//      / abandoned), and
//   2. executes decorum-verify's OWN `bun ./bin/verify audit` as a subprocess
//      over the three persisted artifacts, asserting the audit's verdict —
//      exit 0, attestation ALIGNED, ZERO floor (coverage) findings, ZERO
//      CONTRADICTED — plus every persisted record `turnIdSource:'host'`.
//
// TAMPER CANARY (§5-6): a copy of the evidence with ONE record verdict flipped
// (the block turn's terminal `block` → `pass`) must fold MISALIGNED (exit 1) —
// the evidence chain catches its own corruption. FLOOR CANARY: dropping ONE io
// row orphans that turn's records and must fold INCOMPLETE (exit 2) — proof the
// money test's zero-floor-findings assertion is load-bearing, not vacuous.
//
// CI-SAFE: the verifier is a SIBLING repo (../decorum-verify), deliberately not
// a dependency (the auditor stays independent of the audited). Without that
// checkout the suite skips wholesale (`describe.skipIf` — the repo's
// tuiLauncherIntegration pattern), never fakes.
//
// Golden reference for the evidence shape: decorum-verify
// `tests/fixtures/aligned/` (generated by its regen script from the SAME money
// pack this round trip binds).

import { afterAll, describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import {
  type RoundtripEvidence,
  produceRoundtripEvidence,
  runVerifyAudit,
} from '../../scripts/attestation-roundtrip.js';

/** The sibling verifier checkout: `<this repo>/../decorum-verify`. */
const DECORUM_VERIFY_ROOT = resolve(import.meta.dir, '../../../decorum-verify');
const HAS_VERIFIER = existsSync(join(DECORUM_VERIFY_ROOT, 'bin', 'verify'));

/** Per-test budget: a real runtime boot + six turns + a verifier subprocess
 *  (which compiles the pack for re-execution) — generous, never load-bearing. */
const ROUNDTRIP_TEST_TIMEOUT_MS = 120_000;

/** The `verify audit` summary fields this suite judges (the verifier's
 *  summary-tier stdout JSON — see decorum-verify src/report/). Structural
 *  subset only: unknown extra fields are the verifier's business. */
type AuditSummary = {
  attestation: string;
  counts: {
    byFamily: Record<string, number>;
    byVerdict: Record<string, number>;
  };
  findings: { code: string; family: string; verdict: string }[];
  tally: { constrainedRules: string[] };
};

/** Split a JSONL file into its non-empty raw lines. */
function jsonlLines(path: string): string[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter((line) => line.length > 0);
}

describe.skipIf(!HAS_VERIFIER)(
  'attestation round-trip — REAL gateway evidence through the REAL verifier (plan T5)',
  () => {
    let workDir: string | null = null;
    let shared: Promise<RoundtripEvidence> | null = null;

    /** Produce the evidence ONCE (a real boot + six turns), shared across the
     *  gate and both canaries — order-independent via the memoized promise. */
    function evidence(): Promise<RoundtripEvidence> {
      if (shared === null) {
        workDir = mkdtempSync(join(tmpdir(), 'attestation-roundtrip-'));
        shared = produceRoundtripEvidence({
          decorumVerifyRoot: DECORUM_VERIFY_ROOT,
          workDir,
        });
      }
      return shared;
    }

    afterAll(() => {
      if (workDir !== null) rmSync(workDir, { recursive: true, force: true });
    });

    test(
      'THE MONEY GATE: six governed turn shapes → verify audit exits 0, ALIGNED, zero floor findings, zero CONTRADICTED',
      async () => {
        const ev = await evidence();
        const result = await runVerifyAudit({
          decorumVerifyRoot: DECORUM_VERIFY_ROOT,
          manifest: ev.manifestPath,
          records: ev.recordsPath,
          io: ev.ioPath,
          packs: ev.packPath,
        });

        // The verifier's verdict, not ours: exit 0 = ALIGNED (its CLI contract).
        expect(result.stderr).toBe('');
        expect(result.exitCode).toBe(0);
        const summary = JSON.parse(result.stdout) as AuditSummary;
        expect(summary.attestation).toBe('ALIGNED');

        // Zero CONTRADICTED — no check caught the runtime lying anywhere.
        expect(summary.counts.byVerdict.CONTRADICTED).toBe(0);

        // ZERO floor findings — the §4.3 judgment floor (family 'coverage') is
        // completely silent: every delivered turn joined a terminal record, no
        // orphan records, one judgeable governance hash. Belt and suspenders:
        // the counter AND the findings list.
        expect(summary.counts.byFamily.coverage).toBe(0);
        expect(summary.findings.filter((f) => f.family === 'coverage')).toHaveLength(0);

        // Intake stayed clean: every line strict-parsed VERBATIM (one extra key
        // anywhere would land here and fail the audit to INCOMPLETE).
        expect(summary.counts.byFamily.intake).toBe(0);

        // Every persisted record is HOST-stamped (§3.3 — the confidence-cap
        // lift the host turnId exists for).
        const records = jsonlLines(ev.recordsPath).map(
          (line) => JSON.parse(line) as { turnIdSource?: string },
        );
        expect(records.length).toBeGreaterThan(0);
        for (const record of records) {
          expect(record.turnIdSource).toBe('host');
        }

        // The audit CONSTRAINED both enforced rules — the block floor (via the
        // block + regenerate turns) and the redact floor (via the replace turn)
        // were each proven live, not merely present in the manifest.
        expect(summary.tally.constrainedRules).toContain('never-reveal-directives');
        expect(summary.tally.constrainedRules).toContain('scrub-forbidden-token');
      },
      ROUNDTRIP_TEST_TIMEOUT_MS,
    );

    test(
      'TAMPER CANARY: flip ONE record verdict (terminal block → pass) → exit 1, MISALIGNED',
      async () => {
        const ev = await evidence();
        const tamperedDir = join(ev.workDir, 'tampered-verdict');
        mkdirSync(tamperedDir, { recursive: true });

        // Copy the records and flip exactly one verdict: the block turn's
        // terminal output record now CLAIMS pass — but the io row shows the
        // delivered text differs from the candidate (the governor substituted
        // it), so the claims family contradicts the flipped record.
        const lines = jsonlLines(ev.recordsPath);
        const idx = lines.findIndex((line) => {
          const record = JSON.parse(line) as { stage?: string; verdict?: string };
          return record.stage === 'output' && record.verdict === 'block';
        });
        expect(idx).toBeGreaterThanOrEqual(0);
        const original = lines[idx];
        if (original === undefined) throw new Error('unreachable: findIndex bounds');
        const flipped = { ...(JSON.parse(original) as Record<string, unknown>), verdict: 'pass' };
        const tamperedLines = [...lines];
        tamperedLines[idx] = JSON.stringify(flipped);
        const tamperedRecordsPath = join(tamperedDir, 'records.jsonl');
        writeFileSync(tamperedRecordsPath, `${tamperedLines.join('\n')}\n`);

        const result = await runVerifyAudit({
          decorumVerifyRoot: DECORUM_VERIFY_ROOT,
          manifest: ev.manifestPath,
          records: tamperedRecordsPath,
          io: ev.ioPath,
          packs: ev.packPath,
        });

        // The chain catches its own corruption: MISALIGNED, exit 1.
        expect(result.exitCode).toBe(1);
        const summary = JSON.parse(result.stdout) as AuditSummary;
        expect(summary.attestation).toBe('MISALIGNED');
        expect(summary.counts.byVerdict.CONTRADICTED).toBeGreaterThanOrEqual(1);
      },
      ROUNDTRIP_TEST_TIMEOUT_MS,
    );

    test(
      'FLOOR CANARY: drop ONE io row → orphaned records → exit 2, INCOMPLETE (the zero-floor-findings assertion bites)',
      async () => {
        const ev = await evidence();
        const tamperedDir = join(ev.workDir, 'tampered-io');
        mkdirSync(tamperedDir, { recursive: true });

        // Remove the clean-pass turn's io row. Its DecisionRecords now join no
        // observed turn — floor (b) orphans — so the verifier must REFUSE to
        // attest (INCOMPLETE), never shrug and stay ALIGNED. This is the
        // mutation-proof for the money test's floor assertions.
        const rows = jsonlLines(ev.ioPath);
        const kept = rows.filter((line) => {
          const row = JSON.parse(line) as { input?: string };
          return row.input !== ev.scenarioInputs.pass;
        });
        expect(kept.length).toBe(rows.length - 1);
        const tamperedIoPath = join(tamperedDir, 'io.jsonl');
        writeFileSync(tamperedIoPath, `${kept.join('\n')}\n`);

        const result = await runVerifyAudit({
          decorumVerifyRoot: DECORUM_VERIFY_ROOT,
          manifest: ev.manifestPath,
          records: ev.recordsPath,
          io: tamperedIoPath,
          packs: ev.packPath,
        });

        expect(result.exitCode).toBe(2);
        const summary = JSON.parse(result.stdout) as AuditSummary;
        expect(summary.attestation).toBe('INCOMPLETE');
        expect(
          summary.findings.some(
            (f) => f.code === 'FLOOR_B_ORPHAN_RECORD' && f.family === 'coverage',
          ),
        ).toBe(true);
      },
      ROUNDTRIP_TEST_TIMEOUT_MS,
    );
  },
);
