// Phase 10.8 — `sov init`. Bootstrap a directory into a real harness
// bundle by writing a minimal index.yaml + business/ + harness/schemas/ +
// state/ + skills/ skeleton. v1 contract: refuses to overwrite an
// existing index.yaml unless --force is passed; reads the cwd's
// README.md (when present) to seed business/README.md so the bundle
// has *some* tier-1 content out of the gate.
//
// Per phase-10.8-default-bundle-design.md, the corpus generator is
// minimal in v1 — full design ("what files does sov init actually
// generate when reading a repo?") is deferred to a separate session.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

export type InitOpts = {
  /** Directory to initialize. Default: process.cwd(). */
  cwd?: string;
  /** When true, overwrite an existing index.yaml. Default: false (refuse). */
  force?: boolean;
};

export type InitResult = {
  ok: boolean;
  /** Absolute path to the bundle root (== cwd, returned for the caller's benefit). */
  bundleRoot: string;
  /** Files written, relative to bundleRoot. */
  written: string[];
  /** Free-form error reason when `ok` is false. */
  error?: string;
};

/** Bootstrap a bundle skeleton in `opts.cwd` (default: process.cwd()). */
export function runInit(opts: InitOpts = {}): InitResult {
  const cwd = resolve(opts.cwd ?? process.cwd());
  const indexPath = join(cwd, 'index.yaml');
  if (existsSync(indexPath) && opts.force !== true) {
    return {
      ok: false,
      bundleRoot: cwd,
      written: [],
      error: `index.yaml already exists at ${indexPath} — pass --force to overwrite`,
    };
  }

  const projectName = basename(cwd) || 'my-project';
  const written: string[] = [];

  // Tier-1 README — seed from the cwd's README.md when present, else
  // a minimal stub. The corpus generator is intentionally tiny in v1.
  const seedReadme = readSeedReadme(cwd, projectName);
  mkdirSync(join(cwd, 'business'), { recursive: true });
  writeFileSync(join(cwd, 'business/README.md'), seedReadme, 'utf8');
  written.push('business/README.md');

  // Empty schemas + state + skills directories so the bundle loader is
  // happy and the user has a clear extension surface. Empty marker files
  // keep them tracked in git.
  for (const sub of ['harness/schemas', 'state', 'skills']) {
    mkdirSync(join(cwd, sub), { recursive: true });
    const marker = join(cwd, sub, '.gitkeep');
    if (!existsSync(marker)) {
      writeFileSync(marker, '', 'utf8');
      written.push(`${sub}/.gitkeep`);
    }
  }

  // Manifest. Versioned because the loader reads `index.yaml` first.
  const indexYaml = renderIndexYaml(projectName);
  writeFileSync(indexPath, indexYaml, 'utf8');
  written.push('index.yaml');

  return { ok: true, bundleRoot: cwd, written };
}

/** Pull the cwd's README.md if it exists and quote it under a "Project
 *  README" heading, else write a stub pointing at how to extend the
 *  bundle. */
function readSeedReadme(cwd: string, projectName: string): string {
  const candidate = join(cwd, 'README.md');
  if (existsSync(candidate) && candidate !== join(cwd, 'business/README.md')) {
    try {
      const original = readFileSync(candidate, 'utf8');
      return [
        `# ${projectName} — bundle README`,
        '',
        "_This file is the bundle's tier-1 entry point. The runtime reads it on every session start. Edit freely._",
        '',
        '## Project README (seeded by `sov init`)',
        '',
        original.trim(),
        '',
      ].join('\n');
    } catch {
      // Fall through to the stub.
    }
  }
  return [
    `# ${projectName} — bundle README`,
    '',
    "_This file is the bundle's tier-1 entry point. The runtime reads it on every session start. Edit freely — replace this stub with your project's actual context (architecture, conventions, key files, anything you'd tell a new contributor)._",
    '',
    'See `~/code/sovereign-ai-harness/src/bundle/README.md` for the bundle-as-data contract.',
    '',
  ].join('\n');
}

/** Minimal index.yaml. The loader requires `index.yaml` to exist; it
 *  doesn't strictly require any field in particular. We populate the
 *  obvious ones so a downstream `sov` run produces a coherent splash. */
function renderIndexYaml(projectName: string): string {
  return [
    `repo: ${projectName}`,
    'description: |',
    `  Bundle for ${projectName}, generated by \`sov init\`. Edit business/README.md`,
    '  to give the agent project context. Add custom schemas under harness/schemas/',
    '  and skills under skills/.',
    `updated: ${new Date().toISOString().slice(0, 10)}`,
    'reading_order:',
    '  - bundle-readme',
    'documents:',
    '  - doc_id: bundle-readme',
    '    file: business/README.md',
    `    title: ${projectName} README`,
    '    version: 1',
    '    status: active',
    '    summary: Bundle entry point — project context for the agent.',
    '',
  ].join('\n');
}

/** Format an InitResult for the CLI to print. */
export function formatInitResult(result: InitResult): string {
  if (!result.ok) {
    return `sov init: ${result.error}\n`;
  }
  const lines = [
    `sov init: bootstrapped bundle at ${result.bundleRoot}`,
    '',
    'Wrote:',
    ...result.written.map((f) => `  ${f}`),
    '',
    'Next steps:',
    '  - Edit business/README.md to give the agent your project context.',
    '  - Add skills under skills/ (markdown with `name`, `description`, `whenToUse` frontmatter).',
    '  - Run `sov` from this directory to start the interactive TUI; the upward walk picks up the new index.yaml.',
    '',
  ];
  return `${lines.join('\n')}\n`;
}
